version: '3'
services:
  web:
    image: "anonyfz/workflow-designer-project:develop"
    ports:
     - "8888:8888"
    volumes:
     - "C:/Users/vMS/Desktop/workflow-designer-project:/usr/src/app"
    stdin_open: true
    tty: true
