version: '3'
services:
  web:
    container_name: workflow-designer-development
    image: "anonyfz/workflow-designer-project:develop"
    ports:
     - "8888:8888"
    volumes:
     - .:/usr/src/app
    stdin_open: true
    tty: true
