version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: workflow-designer-development
    ports:
     - "8888:8888"
    volumes:
     - ..:/usr/src/app
    stdin_open: true
    tty: true
